"""server_id add into metrics tables

Revision ID: cdcb8fb5d994
Revises: 225bde88217e
Create Date: 2026-04-01 15:20:35.241922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cdcb8fb5d994"
down_revision: Union[str, Sequence[str], None] = "225bde88217e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Make migration idempotent: check if tables and columns exist before modifying
    inspector = sa.inspect(op.get_bind())
    table_names = inspector.get_table_names()

    # Helper to check if column exists in a table
    def column_exists(table_name: str, column_name: str) -> bool:
        if table_name not in table_names:
            return False
        columns = [col["name"] for col in inspector.get_columns(table_name)]
        return column_name in columns

    # Helper to check if index exists
    def index_exists(table_name: str, index_name: str) -> bool:
        if table_name not in table_names:
            return False
        indexes = inspector.get_indexes(table_name)
        return any(idx["name"] == index_name for idx in indexes)

    # Helper to check if constraint exists
    def constraint_exists(table_name: str, constraint_name: str) -> bool:
        if table_name not in table_names:
            return False
        constraints = inspector.get_unique_constraints(table_name)
        return any(c["name"] == constraint_name for c in constraints)

    # ### commands auto generated by Alembic - please adjust! ###
    # prompt_metrics
    if not column_exists("prompt_metrics", "server_id"):
        op.add_column("prompt_metrics", sa.Column("server_id", sa.String(length=36), nullable=True))
    if index_exists("prompt_metrics", "idx_prompt_metrics_prompt_id_timestamp"):
        op.drop_index(op.f("idx_prompt_metrics_prompt_id_timestamp"), table_name="prompt_metrics")
    if not index_exists("prompt_metrics", "ix_prompt_metrics_server_id"):
        op.create_index(op.f("ix_prompt_metrics_server_id"), "prompt_metrics", ["server_id"], unique=False)

    # prompt_metrics_hourly - use batch mode for SQLite constraint changes
    if "prompt_metrics_hourly" in table_names:
        with op.batch_alter_table("prompt_metrics_hourly", schema=None) as batch_op:
            if not column_exists("prompt_metrics_hourly", "server_id"):
                batch_op.add_column(sa.Column("server_id", sa.String(length=36), nullable=True))
            if constraint_exists("prompt_metrics_hourly", "uq_prompt_metrics_hourly_prompt_hour"):
                batch_op.drop_constraint("uq_prompt_metrics_hourly_prompt_hour", type_="unique")
            if not constraint_exists("prompt_metrics_hourly", "uq_prompt_metrics_hourly_prompt_server_hour"):
                batch_op.create_unique_constraint("uq_prompt_metrics_hourly_prompt_server_hour", ["prompt_id", "server_id", "hour_start"])
        if not index_exists("prompt_metrics_hourly", "ix_prompt_metrics_hourly_server_id"):
            op.create_index(op.f("ix_prompt_metrics_hourly_server_id"), "prompt_metrics_hourly", ["server_id"], unique=False)

    # resource_metrics
    if not column_exists("resource_metrics", "server_id"):
        op.add_column("resource_metrics", sa.Column("server_id", sa.String(length=36), nullable=True))
    if index_exists("resource_metrics", "idx_resource_metrics_resource_id_timestamp"):
        op.drop_index(op.f("idx_resource_metrics_resource_id_timestamp"), table_name="resource_metrics")
    if not index_exists("resource_metrics", "ix_resource_metrics_server_id"):
        op.create_index(op.f("ix_resource_metrics_server_id"), "resource_metrics", ["server_id"], unique=False)

    # resource_metrics_hourly - use batch mode for SQLite constraint changes
    if "resource_metrics_hourly" in table_names:
        with op.batch_alter_table("resource_metrics_hourly", schema=None) as batch_op:
            if not column_exists("resource_metrics_hourly", "server_id"):
                batch_op.add_column(sa.Column("server_id", sa.String(length=36), nullable=True))
            if constraint_exists("resource_metrics_hourly", "uq_resource_metrics_hourly_resource_hour"):
                batch_op.drop_constraint("uq_resource_metrics_hourly_resource_hour", type_="unique")
            if not constraint_exists("resource_metrics_hourly", "uq_resource_metrics_hourly_resource_server_hour"):
                batch_op.create_unique_constraint("uq_resource_metrics_hourly_resource_server_hour", ["resource_id", "server_id", "hour_start"])
        if not index_exists("resource_metrics_hourly", "ix_resource_metrics_hourly_server_id"):
            op.create_index(op.f("ix_resource_metrics_hourly_server_id"), "resource_metrics_hourly", ["server_id"], unique=False)

    # server_metrics
    if index_exists("server_metrics", "idx_server_metrics_server_id_timestamp"):
        op.drop_index(op.f("idx_server_metrics_server_id_timestamp"), table_name="server_metrics")

    # tool_metrics
    if not column_exists("tool_metrics", "server_id"):
        op.add_column("tool_metrics", sa.Column("server_id", sa.String(length=36), nullable=True))
    if index_exists("tool_metrics", "idx_tool_metrics_tool_id_timestamp"):
        op.drop_index(op.f("idx_tool_metrics_tool_id_timestamp"), table_name="tool_metrics")
    if not index_exists("tool_metrics", "ix_tool_metrics_server_id"):
        op.create_index(op.f("ix_tool_metrics_server_id"), "tool_metrics", ["server_id"], unique=False)

    # tool_metrics_hourly - use batch mode for SQLite constraint changes
    if "tool_metrics_hourly" in table_names:
        with op.batch_alter_table("tool_metrics_hourly", schema=None) as batch_op:
            if not column_exists("tool_metrics_hourly", "server_id"):
                batch_op.add_column(sa.Column("server_id", sa.String(length=36), nullable=True))
            if constraint_exists("tool_metrics_hourly", "uq_tool_metrics_hourly_tool_hour"):
                batch_op.drop_constraint("uq_tool_metrics_hourly_tool_hour", type_="unique")
            if not constraint_exists("tool_metrics_hourly", "uq_tool_metrics_hourly_tool_server_hour"):
                batch_op.create_unique_constraint("uq_tool_metrics_hourly_tool_server_hour", ["tool_id", "server_id", "hour_start"])
        if not index_exists("tool_metrics_hourly", "ix_tool_metrics_hourly_server_id"):
            op.create_index(op.f("ix_tool_metrics_hourly_server_id"), "tool_metrics_hourly", ["server_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Make migration idempotent: check if tables and columns exist before modifying
    inspector = sa.inspect(op.get_bind())
    table_names = inspector.get_table_names()

    # Helper to check if column exists in a table
    def column_exists(table_name: str, column_name: str) -> bool:
        if table_name not in table_names:
            return False
        columns = [col["name"] for col in inspector.get_columns(table_name)]
        return column_name in columns

    # Helper to check if index exists
    def index_exists(table_name: str, index_name: str) -> bool:
        if table_name not in table_names:
            return False
        indexes = inspector.get_indexes(table_name)
        return any(idx["name"] == index_name for idx in indexes)

    # Helper to check if constraint exists
    def constraint_exists(table_name: str, constraint_name: str) -> bool:
        if table_name not in table_names:
            return False
        constraints = inspector.get_unique_constraints(table_name)
        return any(c["name"] == constraint_name for c in constraints)

    # ### commands auto generated by Alembic - please adjust! ###
    # tool_metrics_hourly - use batch mode for SQLite constraint changes
    if "tool_metrics_hourly" in table_names:
        if index_exists("tool_metrics_hourly", "ix_tool_metrics_hourly_server_id"):
            op.drop_index(op.f("ix_tool_metrics_hourly_server_id"), table_name="tool_metrics_hourly")
        with op.batch_alter_table("tool_metrics_hourly", schema=None) as batch_op:
            if constraint_exists("tool_metrics_hourly", "uq_tool_metrics_hourly_tool_server_hour"):
                batch_op.drop_constraint("uq_tool_metrics_hourly_tool_server_hour", type_="unique")
            if not constraint_exists("tool_metrics_hourly", "uq_tool_metrics_hourly_tool_hour"):
                batch_op.create_unique_constraint("uq_tool_metrics_hourly_tool_hour", ["tool_id", "hour_start"])
            if column_exists("tool_metrics_hourly", "server_id"):
                batch_op.drop_column("server_id")

    # tool_metrics
    if "tool_metrics" in table_names:
        if index_exists("tool_metrics", "ix_tool_metrics_server_id"):
            op.drop_index(op.f("ix_tool_metrics_server_id"), table_name="tool_metrics")
        if not index_exists("tool_metrics", "idx_tool_metrics_tool_id_timestamp"):
            op.create_index(op.f("idx_tool_metrics_tool_id_timestamp"), "tool_metrics", ["tool_id", "timestamp"], unique=False)
        if column_exists("tool_metrics", "server_id"):
            op.drop_column("tool_metrics", "server_id")

    # server_metrics
    if "server_metrics" in table_names:
        if not index_exists("server_metrics", "idx_server_metrics_server_id_timestamp"):
            op.create_index(op.f("idx_server_metrics_server_id_timestamp"), "server_metrics", ["server_id", "timestamp"], unique=False)

    # resource_metrics_hourly - use batch mode for SQLite constraint changes
    if "resource_metrics_hourly" in table_names:
        if index_exists("resource_metrics_hourly", "ix_resource_metrics_hourly_server_id"):
            op.drop_index(op.f("ix_resource_metrics_hourly_server_id"), table_name="resource_metrics_hourly")
        with op.batch_alter_table("resource_metrics_hourly", schema=None) as batch_op:
            if constraint_exists("resource_metrics_hourly", "uq_resource_metrics_hourly_resource_server_hour"):
                batch_op.drop_constraint("uq_resource_metrics_hourly_resource_server_hour", type_="unique")
            if not constraint_exists("resource_metrics_hourly", "uq_resource_metrics_hourly_resource_hour"):
                batch_op.create_unique_constraint("uq_resource_metrics_hourly_resource_hour", ["resource_id", "hour_start"])
            if column_exists("resource_metrics_hourly", "server_id"):
                batch_op.drop_column("server_id")

    # resource_metrics
    if "resource_metrics" in table_names:
        if index_exists("resource_metrics", "ix_resource_metrics_server_id"):
            op.drop_index(op.f("ix_resource_metrics_server_id"), table_name="resource_metrics")
        if not index_exists("resource_metrics", "idx_resource_metrics_resource_id_timestamp"):
            op.create_index(op.f("idx_resource_metrics_resource_id_timestamp"), "resource_metrics", ["resource_id", "timestamp"], unique=False)
        if column_exists("resource_metrics", "server_id"):
            op.drop_column("resource_metrics", "server_id")

    # prompt_metrics_hourly - use batch mode for SQLite constraint changes
    if "prompt_metrics_hourly" in table_names:
        if index_exists("prompt_metrics_hourly", "ix_prompt_metrics_hourly_server_id"):
            op.drop_index(op.f("ix_prompt_metrics_hourly_server_id"), table_name="prompt_metrics_hourly")
        with op.batch_alter_table("prompt_metrics_hourly", schema=None) as batch_op:
            if constraint_exists("prompt_metrics_hourly", "uq_prompt_metrics_hourly_prompt_server_hour"):
                batch_op.drop_constraint("uq_prompt_metrics_hourly_prompt_server_hour", type_="unique")
            if not constraint_exists("prompt_metrics_hourly", "uq_prompt_metrics_hourly_prompt_hour"):
                batch_op.create_unique_constraint("uq_prompt_metrics_hourly_prompt_hour", ["prompt_id", "hour_start"])
            if column_exists("prompt_metrics_hourly", "server_id"):
                batch_op.drop_column("server_id")

    # prompt_metrics
    if "prompt_metrics" in table_names:
        if index_exists("prompt_metrics", "ix_prompt_metrics_server_id"):
            op.drop_index(op.f("ix_prompt_metrics_server_id"), table_name="prompt_metrics")
        if not index_exists("prompt_metrics", "idx_prompt_metrics_prompt_id_timestamp"):
            op.create_index(op.f("idx_prompt_metrics_prompt_id_timestamp"), "prompt_metrics", ["prompt_id", "timestamp"], unique=False)
        if column_exists("prompt_metrics", "server_id"):
            op.drop_column("prompt_metrics", "server_id")
    # ### end Alembic commands ###
