"""server_id add into metrics tables

Revision ID: cdcb8fb5d994
Revises: 225bde88217e
Create Date: 2026-04-01 15:20:35.241922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcb8fb5d994'
down_revision: Union[str, Sequence[str], None] = '225bde88217e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_prompt_metrics_server_id'), 'prompt_metrics', ['server_id'], unique=False)
    op.add_column('prompt_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_prompt_metrics_hourly_prompt_hour'), 'prompt_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_prompt_metrics_hourly_server_id'), 'prompt_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_prompt_metrics_hourly_prompt_server_hour', 'prompt_metrics_hourly', ['prompt_id', 'server_id', 'hour_start'])
    op.add_column('resource_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_resource_metrics_server_id'), 'resource_metrics', ['server_id'], unique=False)
    op.add_column('resource_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_resource_metrics_hourly_resource_hour'), 'resource_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_resource_metrics_hourly_server_id'), 'resource_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_resource_metrics_hourly_resource_server_hour', 'resource_metrics_hourly', ['resource_id', 'server_id', 'hour_start'])
    op.add_column('tool_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tool_metrics_server_id'), 'tool_metrics', ['server_id'], unique=False)
    op.add_column('tool_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_tool_metrics_hourly_tool_hour'), 'tool_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_tool_metrics_hourly_server_id'), 'tool_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_tool_metrics_hourly_tool_server_hour', 'tool_metrics_hourly', ['tool_id', 'server_id', 'hour_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_metrics_hourly_tool_server_hour', 'tool_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_tool_metrics_hourly_server_id'), table_name='tool_metrics_hourly')
    op.create_unique_constraint(op.f('uq_tool_metrics_hourly_tool_hour'), 'tool_metrics_hourly', ['tool_id', 'hour_start'])
    op.drop_column('tool_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_tool_metrics_server_id'), table_name='tool_metrics')
    op.drop_column('tool_metrics', 'server_id')
    op.drop_constraint('uq_resource_metrics_hourly_resource_server_hour', 'resource_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_resource_metrics_hourly_server_id'), table_name='resource_metrics_hourly')
    op.create_unique_constraint(op.f('uq_resource_metrics_hourly_resource_hour'), 'resource_metrics_hourly', ['resource_id', 'hour_start'])
    op.drop_column('resource_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_resource_metrics_server_id'), table_name='resource_metrics')
    op.drop_column('resource_metrics', 'server_id')
    op.drop_constraint('uq_prompt_metrics_hourly_prompt_server_hour', 'prompt_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_prompt_metrics_hourly_server_id'), table_name='prompt_metrics_hourly')
    op.create_unique_constraint(op.f('uq_prompt_metrics_hourly_prompt_hour'), 'prompt_metrics_hourly', ['prompt_id', 'hour_start'])
    op.drop_column('prompt_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_prompt_metrics_server_id'), table_name='prompt_metrics')
    op.drop_column('prompt_metrics', 'server_id')
    # ### end Alembic commands ###
